exports.dataTest = [
  {
    id: 1,
    nom: "Med Alcool",
    identifiant: "HV15T",
    fournisseur: "PFIZER",
    expiration: "2023-08-02",
    quantité: "60",
  },
  {
    id: 2,
    nom: "Dakin solution 0.5%",
    identifiant: "HV155T",
    fournisseur: "AMKLI",
    expiration: "2023-10-02",
    quantité: "20",
  },
  {
    id: 2,
    nom: "Dakin solution 0.5%",
    identifiant: "HV155T",
    fournisseur: "AMKLI",
    expiration: "2023-10-02",
    quantité: "20",
  },
  {
    id: 3,
    nom: "Tranlugel gel",
    identifiant: "LKIO85",
    fournisseur: "PFIZER",
    expiration: "2029-02-02",
    quantité: "20",
  },
  {
    id: 4,
    nom: "POLYMIXINE",
    identifiant: "LKOJ75",
    fournisseur: "LINOM",
    expiration: "2029-11-02",
    quantité: "10",
  },
  {
    id: 5,
    nom: "GLUCOSE",
    identifiant: "IOUTEJ95",
    fournisseur: "KIOLI",
    expiration: "2026-10-02",
    quantité: "5",
  },
  {
    id: 6,
    nom: "GLYCEROLE",
    identifiant: "IKLOJ784",
    fournisseur: "KLOITY",
    expiration: "2028-09-02",
    quantité: "8",
  },
  {
    id: 7,
    nom: "TRANLUGEL GEL",
    identifiant: "LKIO85",
    fournisseur: "PFIZER",
    expiration: "2029-02-02",
    quantité: "20",
  },
  {
    id: 8,
    nom: "POLYMIXINE",
    identifiant: "LKOJ75",
    fournisseur: "LINOM",
    expiration: "2029-11-02",
    quantité: "10",
  },
  {
    id: 9,
    nom: "Med Alcool",
    identifiant: "HV15T",
    fournisseur: "PFIZER",
    expiration: "2023-08-02",
    quantité: "60",
  },
  {
    id: 10,
    nom: "Dakin solution 0.5%",
    identifiant: "HV155T",
    fournisseur: "AMKLI",
    expiration: "2023-10-02",
    quantité: "20",
  },
];
